export interface KnowledgeEntry {
  id: string;
  keywords: string[];
  answers: { en: string; fil: string; taglish: string };
  allowDuringDraft: boolean;
  source: 'chatbotContext.md';
}

function entry(
  id: string,
  keywords: string[],
  en: string,
  fil: string,
  taglish: string,
): KnowledgeEntry {
  return { id, keywords, answers: { en, fil, taglish }, allowDuringDraft: true, source: 'chatbotContext.md' };
}

// Reviewed entries distilled from the approved sections of chatbotContext.md.
// Proposed directories, hotlines, live weather, and evacuation-center details
// are absent until a verified system-backed source is available.
export const KNOWLEDGE_CATALOG: KnowledgeEntry[] = [
  entry('disastrace-purpose', ['what is disastrace', 'ano ang disastrace', 'disastrace purpose', 'para saan ang disastrace'], 'DisasTRACE helps Baliwag residents report incidents, receive verified emergency updates, and support coordination with the Baliwag CDRRMO.', 'Tinutulungan ng DisasTRACE ang mga residente ng Baliwag na mag-report ng insidente, makatanggap ng beripikadong update, at masuportahan ang koordinasyon ng Baliwag CDRRMO.', 'Ang DisasTRACE ay tumutulong sa Baliwag residents na mag-report ng incident, makatanggap ng verified updates, at masuportahan ang CDRRMO coordination.'),
  entry('disastrace-process', ['how does disastrace work', 'paano gumagana ang disastrace', 'disastrace process'], 'A public user submits an incident report in DisasTRACE. Authorized personnel review it, coordinate the appropriate response, and use available dispatch and tracking tools.', 'Nagsusumite ang public user ng incident report sa DisasTRACE. Sinusuri ito ng authorized personnel, kino-coordinate ang angkop na tugon, at ginagamit ang available dispatch at tracking tools.', 'A public user submits an incident report, then authorized personnel review it, coordinate the response, at use available dispatch and tracking tools.'),
  entry('chatbot-purpose', ['what can you do', 'what can the bot do', 'ano kaya mo', 'chatbot purpose'], 'I can guide incident reports and provide approved DisasTRACE, emergency-safety, preparedness, and Baliwag CDRRMO information.', 'Maaari kitang gabayan sa incident report at magbigay ng aprubadong impormasyon tungkol sa DisasTRACE, kaligtasan, paghahanda, at Baliwag CDRRMO.', 'I can guide your incident report at magbigay ng approved DisasTRACE, safety, preparedness, at Baliwag CDRRMO information.'),
  entry('chatbot-limitations', ['chatbot limitations', 'alam ba ng chatbot lahat', 'replace emergency responders', 'doctor ba ang chatbot'], 'The chatbot uses available reviewed knowledge. It does not replace emergency responders, medical professionals, or official authorities, and it does not claim unverified real-time emergency information.', 'Gumagamit ang chatbot ng available at sinuring kaalaman. Hindi nito pinapalitan ang emergency responders, medical professionals, o opisyal na awtoridad at hindi ito nagkukumpirma ng hindi beripikadong real-time information.', 'The chatbot uses reviewed knowledge. Hindi nito pinapalitan ang responders, medical professionals, or authorities, at hindi ito nagco-confirm ng unverified live information.'),
  entry('disaster-preparedness', ['disaster preparedness', 'maghanda sa disaster', 'bago ang disaster', 'before a disaster'], 'Disaster preparedness means planning ahead, knowing local hazards, preparing supplies, and following verified official warnings and evacuation instructions.', 'Ang disaster preparedness ay maagang pagpaplano, pagkilala sa panganib, paghahanda ng gamit, at pagsunod sa beripikadong babala at evacuation instruction.', 'Disaster preparedness means magplano nang maaga, maghanda ng supplies, at sumunod sa verified warnings at evacuation instructions.'),
  entry('emergency-plan', ['emergency plan', 'family emergency plan', 'planong pang emergency'], 'Create a family emergency plan with meeting places, emergency contacts, evacuation routes, individual responsibilities, and a plan for children, older adults, pets, and persons with disabilities.', 'Gumawa ng family emergency plan na may meeting place, emergency contacts, evacuation routes, tungkulin ng bawat isa, at plano para sa bata, matatanda, alagang hayop, at persons with disabilities.', 'Create a family emergency plan with meeting places, contacts, routes, at malinaw na responsibilities ng bawat isa.'),
  entry('go-bag', ['go bag', 'emergency bag', 'emergency kit', 'go-bag'], 'Prepare a go-bag with water, ready-to-eat food, medicines, first-aid supplies, flashlight, batteries or power bank, radio, whistle, masks, clothes, hygiene items, and copies of important documents.', 'Maghanda ng go-bag na may tubig, pagkaing handa nang kainin, gamot, first-aid supplies, flashlight, baterya o power bank, radyo, pito, mask, damit, hygiene items, at kopya ng mahahalagang dokumento.', 'Prepare a go-bag with water, food, medicines, first-aid supplies, flashlight, power bank, whistle, clothes, hygiene items, at copies ng important documents.'),
  entry('emergency-water', ['emergency water', 'tubig sa emergency kit', 'gaano kahalaga ang tubig', 'drinking water supply'], 'Drinking water is one of the most important emergency supplies. Keep an adequate supply at home and bring drinking water when evacuating.', 'Ang inuming tubig ay isa sa pinakamahalagang emergency supplies. Magtabi ng sapat sa bahay at magdala kapag lumilikas.', 'Drinking water is an important emergency supply. Magtabi ng sapat sa bahay at magdala when evacuating.'),
  entry('flood-electricity', ['electricity during a flood', 'kuryente kapag baha', 'appliances na nabasa', 'wet electrical'], 'Floodwater and electricity are extremely dangerous together. Do not touch wet or submerged electrical equipment, outlets, wires, or appliances. Move away and seek help from the appropriate authorities.', 'Lubhang mapanganib ang baha at kuryente. Huwag hawakan ang basâ o nakalubog na electrical equipment, outlet, wire, o appliance. Lumayo at humingi ng tulong sa awtoridad.', 'Floodwater and electricity are dangerous. Huwag hawakan ang wet or submerged equipment, outlets, wires, or appliances; move away and seek official help.'),
  entry('flood-safety', ['flood safety', 'ano gagawin sa baha', 'during a flood', 'safe lumusong', 'walk through floodwater'], 'During flooding, move to higher ground when told to evacuate, avoid walking or driving through floodwater, keep away from electrical hazards, and follow verified local advisories.', 'Kapag may baha, pumunta sa mataas na lugar kapag inutusang lumikas, huwag lumusong o magmaneho sa baha, lumayo sa panganib ng kuryente, at sumunod sa beripikadong abiso.', 'During a flood, move to higher ground, huwag lumusong o mag-drive sa floodwater, avoid electrical hazards, at follow verified advisories.'),
  entry('typhoon-during', ['during a typhoon', 'habang may bagyo', 'malakas ang hangin', 'safe ba lumabas'], 'During a typhoon, stay indoors in a safe area away from windows and unsecured objects. Monitor official announcements and evacuate if authorities instruct you.', 'Habang may bagyo, manatili sa ligtas na bahagi ng bahay at lumayo sa bintana at bagay na maaaring liparin. Bantayan ang opisyal na abiso at lumikas kapag inutusan.', 'During a typhoon, stay indoors away from windows and unsecured objects. Monitor official announcements at evacuate kapag inutusan.'),
  entry('typhoon-preparedness', ['prepare for typhoon', 'before a typhoon', 'bago ang bagyo', 'paano maghanda sa typhoon', 'heavy rain preparation'], 'Before heavy rain or a typhoon, secure your home, charge devices, prepare your go-bag, monitor official advisories, and evacuate early when authorities instruct you.', 'Bago ang malakas na ulan o bagyo, tiyaking ligtas ang bahay, i-charge ang devices, ihanda ang go-bag, bantayan ang opisyal na abiso, at lumikas nang maaga kapag inutusan.', 'Before a typhoon, secure your home, charge devices, prepare your go-bag, monitor official advisories, at evacuate early kapag inutusan.'),
  entry('earthquake-after', ['after an earthquake', 'pagkatapos ng lindol', 'aftershock', 'safe na ba lumabas'], 'After an earthquake, check for injuries when safe, expect aftershocks, avoid damaged buildings, fire, and electrical hazards, and follow official instructions before returning.', 'Pagkatapos ng lindol, tingnan kung may nasaktan kapag ligtas, mag-ingat sa aftershock, sirang gusali, sunog, at panganib ng kuryente, at sundin ang opisyal na tagubilin bago bumalik.', 'After an earthquake, check for injuries, expect aftershocks, avoid damaged buildings and electrical hazards, at follow official instructions.'),
  entry('earthquake-safety', ['during an earthquake', 'kapag lumindol', 'lumilindol', 'drop cover hold'], 'During an earthquake, Drop, Cover, and Hold On. Stay away from glass and heavy objects, then check for injuries and follow official instructions after the shaking stops.', 'Kapag lumilindol, Drop, Cover, and Hold On. Lumayo sa salamin at mabibigat na bagay, tingnan kung may nasaktan, at sumunod sa opisyal na tagubilin pagkatapos ng pagyanig.', 'During an earthquake, Drop, Cover, and Hold On. Lumayo sa glass at heavy objects, then check injuries and follow official instructions.'),
  entry('fire-smoke', ['what to do if there is smoke', 'maraming usok', 'puno ng usok', 'smoke in building'], 'Stay as low as possible to avoid inhaling smoke and move toward a safe exit. Do not enter or remain in a smoke-filled area if it can be avoided.', 'Manatiling mababa upang hindi malanghap ang usok at pumunta sa ligtas na labasan. Huwag pumasok o manatili sa lugar na puno ng usok kung maiiwasan.', 'Stay low to avoid inhaling smoke and move to a safe exit. Huwag pumasok o manatili sa smoke-filled area kung maiiwasan.'),
  entry('fire-safety', ['fire safety', 'ano gagawin sa sunog', 'during a fire'], 'If there is a fire, leave through the safest available exit, stay low under smoke, do not use elevators, and do not return until responders say it is safe.', 'Kapag may sunog, lumabas sa pinakaligtas na exit, yumuko sa ilalim ng usok, huwag gumamit ng elevator, at huwag bumalik hangga’t hindi sinasabing ligtas ng responders.', 'If there is a fire, use the safest exit, stay low under smoke, huwag gumamit ng elevator, at huwag bumalik until responders say it is safe.'),
  entry('bleeding-first-aid', ['bleeding', 'pagdurugo', 'dumudugo'], 'For serious bleeding, call for emergency help, apply firm direct pressure with clean cloth or gauze, and keep pressure in place while waiting for responders.', 'Sa malakas na pagdurugo, humingi ng emergency help, idiin nang maayos ang malinis na tela o gauze sa sugat, at panatilihin ang pressure habang naghihintay ng responders.', 'For serious bleeding, call emergency help, apply firm direct pressure gamit ang clean cloth or gauze, at keep the pressure while waiting.'),
  entry('burn-first-aid', ['burn first aid', 'paso', 'napaso'], 'Cool a minor burn under clean, cool running water. Do not apply ice, toothpaste, or grease. Seek emergency help for severe, large, electrical, chemical, facial, or airway burns.', 'Palamigin ang maliit na paso sa malinis at malamig na dumadaloy na tubig. Huwag lagyan ng yelo, toothpaste, o grasa. Humingi ng emergency help para sa malubha o malawak na paso.', 'Cool a minor burn under clean running water. Huwag gumamit ng ice, toothpaste, or grease, at seek emergency help for severe burns.'),
  entry('unconscious-first-aid', ['unconscious person', 'walang malay', 'hindi nagrerespond'], 'Call emergency services, check breathing, keep the airway clear, and follow dispatcher instructions. Do not give food or drink to an unconscious person.', 'Tumawag ng emergency services, tingnan kung humihinga, panatilihing bukas ang daanan ng hangin, at sundin ang dispatcher. Huwag painumin o pakainin ang taong walang malay.', 'Call emergency services, check breathing, keep the airway clear, at follow dispatcher instructions. Huwag bigyan ng food or drink.'),
  entry('evacuation-items', ['bring during evacuation', 'dadalhin kapag evacuation', 'kailangan sa evacuation center'], 'Bring water, food, medicines, important documents, a flashlight, batteries, communication devices, clothing, hygiene supplies, and other necessary personal items.', 'Magdala ng tubig, pagkain, gamot, mahahalagang dokumento, flashlight, baterya, communication device, damit, hygiene supplies, at iba pang kailangang personal na gamit.', 'Bring water, food, medicines, documents, flashlight, batteries, communication devices, clothes, hygiene supplies, at other needed personal items.'),
  entry('evacuation', ['evacuate', 'what is evacuation', 'ano ang evacuation', 'lumikas'], 'Evacuate when local authorities direct you. Bring your go-bag, assist vulnerable household members when safe, and rely on official evacuation information.', 'Lumikas kapag inutusan ng lokal na awtoridad. Dalhin ang go-bag, tulungan ang vulnerable na kasama kapag ligtas, at umasa sa opisyal na evacuation information.', 'Evacuate kapag inutusan ng authorities, bring your go-bag, assist vulnerable household members when safe, at follow official information.'),
  entry('baliwag-hazards', ['hazards in baliwag', 'hazards sa baliwag', 'disasters sa baliwag'], 'City information identifies flooding and earthquake-related ground shaking among Baliwag hazards. Monitor official CDRRMO and City Government announcements for current warnings.', 'Kabilang ang pagbaha at pagyanig na dulot ng lindol sa mga hazard na tinukoy sa Baliwag. Bantayan ang opisyal na CDRRMO at City Government announcements.', 'Flooding and earthquake-related ground shaking are identified Baliwag hazards. Monitor official CDRRMO and City Government warnings.'),
  entry('baliwag-preparedness', ['preparedness programs in baliwag', 'training ba ang cdrrmo', 'disaster preparedness activities sa baliwag'], 'Baliwag CDRRMO conducts preparedness activities and training including first aid, basic life support and CPR, aquatic safety and rescue, incident command systems, and ambulance management.', 'Nagsasagawa ang Baliwag CDRRMO ng preparedness activities at training gaya ng first aid, basic life support at CPR, aquatic safety and rescue, incident command systems, at ambulance management.', 'Baliwag CDRRMO conducts preparedness training including first aid, CPR, aquatic rescue, incident command systems, at ambulance management.'),
  entry('emergency-agencies', ['emergency responders in baliwag', 'agencies ang tumutulong', 'who responds to emergencies', 'sino tumutulong kapag disaster'], 'Depending on the emergency, response may involve CDRRMO, the Bureau of Fire Protection, the Philippine National Police, ambulance or medical personnel, barangay officials, and other appropriate agencies.', 'Depende sa emergency, maaaring tumugon ang CDRRMO, Bureau of Fire Protection, Philippine National Police, ambulance o medical personnel, barangay officials, at iba pang angkop na ahensiya.', 'Depending on the emergency, CDRRMO, BFP, PNP, ambulance or medical personnel, barangay officials, at other appropriate agencies may respond.'),
  entry('cdrrmo-role', ['cdrrmo role', 'baliwag cdrrmo', 'ano ginagawa ng cdrrmo', 'pacc role'], 'Baliwag CDRRMO coordinates local disaster-risk reduction and emergency response. DisasTRACE supports reporting and coordination, while responders and PACC make operational decisions.', 'Ang Baliwag CDRRMO ang nagko-coordinate ng disaster-risk reduction at emergency response. Sinusuportahan ng DisasTRACE ang reporting at coordination, habang responders at PACC ang gumagawa ng operational decisions.', 'Baliwag CDRRMO coordinates disaster-risk reduction and emergency response. DisasTRACE supports reporting, while responders and PACC handle operational decisions.'),
  entry('official-advisories', ['official advisories', 'official announcement', 'evacuation order', 'emergency updates'], 'Use verified Baliwag City or CDRRMO channels and in-app announcements for official emergency advisories. The chatbot does not invent or confirm live conditions.', 'Gamitin ang beripikadong Baliwag City o CDRRMO channels at in-app announcements para sa opisyal na abiso. Hindi nag-iimbento o nagkukumpirma ng live condition ang chatbot.', 'Use verified Baliwag City or CDRRMO channels and in-app announcements. Hindi nagco-confirm ng live conditions ang chatbot.'),
];

export function findKnowledge(message: string) {
  const normalized = message.toLowerCase();
  return KNOWLEDGE_CATALOG.find((knowledge) => knowledge.keywords.some((keyword) => normalized.includes(keyword)));
}

export function getKnowledgeAnswer(entry: KnowledgeEntry, language: 'en' | 'fil' | 'taglish') {
  return entry.answers[language];
}
